// Generated by CoffeeScript 1.6.2
var RoyCompiler, capitalize, formatClassName, roy;

roy = require('roy');

capitalize = function(string) {
  return (string[0] || '').toUpperCase() + string.slice(1);
};

formatClassName = function(filename) {
  return filename.split('_').map(capitalize).join('');
};

module.exports = RoyCompiler = (function() {
  RoyCompiler.prototype.brunchPlugin = true;

  RoyCompiler.prototype.type = 'javascript';

  RoyCompiler.prototype.extension = 'roy';

  RoyCompiler.prototype.generators = {
    backbone: (function() {
      var types;

      types = {};
      ['collection', 'model', 'router', 'view'].forEach(function(type) {
        var parent;

        parent = formatClassName(type);
        return types[type] = function(fileName) {
          var className;

          className = formatClassName(fileName);
          return '';
        };
      });
      return types;
    })()
  };

  function RoyCompiler(config) {
    this.config = config;
    null;
  }

  RoyCompiler.prototype.compile = function(data, path, callback) {
    var err, error, result;

    try {
      return result = (roy.compile(data)).output;
    } catch (_error) {
      err = _error;
      return error = err;
    } finally {
      callback(error, result);
    }
  };

  return RoyCompiler;

})();
